[package]
name = "encrypted-ixs"
version = "0.1.0"
edition = "2021"

[features]
default = ["circuits"]
circuits = ["arcis-imports"]

[dependencies]
arcis-imports = { version = "0.3.0", optional = true }